version: 0.6.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
nuget:
  account_feed: true
  project_feed: true
build_script:
- pwsh: >-
    dotnet restore

    dotnet build
test_script:
- pwsh: >-
    dotnet test  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover



    dotnet tool install coveralls.net --version 1.0.0 --tool-path tools


    ./tools/csmacnz.Coveralls.exe --useRelativePaths --multiple -i "opencover=Regulus.Utility.Test\coverage.opencover.xml;opencvoer=Regulus.Remote.Test\coverage.opencover.xml;opencvoer=Regulus.Serialization.Test\coverage.opencover.xml;opencvoer=Regulus.Remote.Protocol.Test\coverage.opencover.xml;opencvoer=Regulus.Remote.Client.JIT.Test\coverage.opencover.xml;opencvoer=Regulus.Network.Test\coverage.opencover.xml;opencvoer=Regulus.LockstepTest\coverage.opencover.xml;opencvoer=Regulus.LockstepTest\coverage.opencover.xml;opencvoer=Regulus.BehaviourTree.Test\coverage.opencover.xml;opencvoer=Regulus.Application.Protocol.Generator.Test\coverage.opencover.xml" --repoToken 4aL4sSKKvWbGicuk2DRR7QvSJnC4e3Hsq
artifacts:
- path: artifact\Library\Server
  name: Server
- path: artifact\Library\Client
  name: Client
- path: artifact\Library\BehaviourTree
  name: BehaviourTree
- path: artifact\Tool
  name: Tool
- path: artifact\Library\Serialization
  name: Serialization
before_deploy:
- cmd: build_package.cmd
deploy:
- provider: GitHub
  auth_token:
    secure: /AfJAx3kxJ0kcGiZVCl5U7v3f9Z0qIDDN5L+ckDjxzkULqDK0fhwWVgcqRNukVln
  draft: true
  prerelease: true
- provider: NuGet
  api_key:
    secure: MpSZN9rbs/UO67xFMkdfsETL16yG2KY0h3S53s13iG8WOFPamFIXg44GpbM4T7qX
  on:
    branch: master