version: 0.6.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
before_build:
- pwsh: >-
    dotnet restore

    dotnet tool install --global coveralls.net
build:
  publish_nuget: true
  verbosity: minimal
after_build:
- ps: >-
    Get-ChildItem **\BehaviourTree.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

    Get-ChildItem **\Client.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

    Get-ChildItem **\Server.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

    Get-ChildItem **\Tool.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test_script:
- pwsh: >-
    dotnet test  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover


    .\csmacnz.Coveralls.exe --useRelativePaths --multiple -i "opencover=Regulus.Utility.Test\coverage.opencover.xml;opencvoer=Regulus.Remote.Test\coverage.opencover.xml" --repoToken 4aL4sSKKvWbGicuk2DRR7QvSJnC4e3Hsq
artifacts:
- path: artifact\Library\Server
  name: Server
- path: artifact\Library\Client
  name: Client
- path: artifact\Library\BehaviourTree
  name: BehaviourTree
- path: artifact\Tool
  name: Tool
- path: artifact\Library\Serialization
  name: Serialization
deploy:
- provider: GitHub
  auth_token:
    secure: /AfJAx3kxJ0kcGiZVCl5U7v3f9Z0qIDDN5L+ckDjxzkULqDK0fhwWVgcqRNukVln
  draft: true
- provider: NuGet
  api_key:
    secure: MpSZN9rbs/UO67xFMkdfsETL16yG2KY0h3S53s13iG8WOFPamFIXg44Gpb
